Cleanup

diff --git a/minecraft-server b/minecraft-server
--- a/minecraft-server
+++ b/minecraft-server
@@ -36,7 +36,7 @@ MINECRAFT_HOME=~/bin/minecraft.server/Minecraft.$MINECRAFT_VERSION
 MINECRAFT_JAR=server.jar
 
 # Location of the Minecraft server .jar file online
-MINECRAFT_URL=https://launcher.mojang.com/v1/objects/f1a0073671057f01aa843443fef34330281333ce/$MINECRAFT_JAR
+# MINECRAFT_URL=https://launcher.mojang.com/v1/objects/f1a0073671057f01aa843443fef34330281333ce/$MINECRAFT_JAR
 
 # Location of the start script and the anounce script for Minecraft
 MCSTART_URL=https://github.com/vonschutter/Ubuntu-Minecraft-Server-Manager/raw/master/bin/minecraft.server/Minecraft.Latest
@@ -58,11 +58,11 @@ function check_dependencies ()
 #---------------------------------------------------------------
 echo "Checking for script dependencies and install if not there..."
 #---------------------------------------------------------------
-    if hash $1 2>/dev/null; then
+    if hash "$1" 2>/dev/null; then
         echo "I found that $1 is present on this system... thankyou for that! "
     else
         echo "You seem to have no $1... I will try to get it... "
-        install_software $1
+        install_software "$1"
             if [ $? != 0 ];
             then
                 echo "That install didn't work out so well."
@@ -76,14 +76,14 @@ echo "Checking for script dependencies and install if not there..."
 install_software () 
 {
 	if hash pkcon 2>/dev/null; then
-		sudo pkcon -y  install $@
+		sudo pkcon -y  install "$@"
 	elif hash yum 2>/dev/null; then
-		sudo yum -y  install $@
+		sudo yum -y  install "$@"
 	elif hash zypper 2>/dev/null; then
-		sudo zypper install -y $@
+		sudo zypper install -y "$@"
 	elif hash apt-get 2>/dev/null; then
 		export DEBIAN_FRONTEND=noninteractive
-		sudo apt-get -y -qq --allow-change-held-packages --ignore-missing install $@
+		sudo apt-get -y -qq --allow-change-held-packages --ignore-missing install "$@"
 	else
 		echo -e $YELLOW "This system does not seem to have a software managment system" $ENDCOLOR
 		_cleanup
@@ -151,25 +151,24 @@ function check_java (){
 
 
 function find_active_newtork_interface (){
-    NETINT=`ip addr | awk '/state UP/ {print $2}' |grep -v "br*" |grep -v "wlp*" | head --bytes -2 `
+    NETINT=$(ip addr | awk '/state UP/ {print $2}' |grep -v "br*" |grep -v "wlp*" | head --bytes -2 )
     echo "Active network interface is: $NETINT"
-    export $NETINT
 }
 
 
  function minecraft_update() {
     # Get minecraft version publication file and get the latest server URL
-    cd $MINECRAFT_HOME  
+    cd $MINECRAFT_HOME || { echo "Failure change to Minecraft folder. Is it there?"; exit 1; }
     wget -q -O $MINECRAFT_HOME/versions --no-check-certificate https://launchermeta.mojang.com/mc/game/version_manifest.json
-    JSONVERSION=`cat versions | python -c "exec(\"import json,sys\nobj=json.load(sys.stdin)\nversion=obj['latest']['release']\nfor v in obj['versions']:\n   if v['id']==version:\n    print(v['url'])\")"`
+    JSONVERSION=$(cat versions | python -c "exec(\"import json,sys\nobj=json.load(sys.stdin)\nversion=obj['latest']['release']\nfor v in obj['versions']:\n   if v['id']==version:\n    print(v['url'])\")")
     wget -q -O $MINECRAFT_HOME/versions --no-check-certificate $JSONVERSION
-    MC_SERVER_URL=`cat versions | python -c 'import json,sys;obj=json.load(sys.stdin);print(obj["downloads"]["server"]["url"])'`
+    MC_SERVER_URL=$(cat versions | python -c 'import json,sys;obj=json.load(sys.stdin);print(obj["downloads"]["server"]["url"])')
     rm $MINECRAFT_HOME/versions
 
     # Download the latest minecraft vesrion and check if it is the same as the one installed
      wget -q -O $MINECRAFT_HOME/minecraft_server.jar.update --no-check-certificate $MC_SERVER_URL
      if [ -f $MINECRAFT_HOME/minecraft_server.jar.update ] ; then
-       if `diff $MINECRAFT_HOME/$MINECRAFT_JAR $MINECRAFT_HOME/minecraft_server.jar.update >/dev/null` ; then
+       if diff $MINECRAFT_HOME/$MINECRAFT_JAR $MINECRAFT_HOME/minecraft_server.jar.update >/dev/null ; then
          echo "You are already running the latest version of $MINECRAFT_JAR."
        else
         mv $MINECRAFT_JAR $MINECRAFT_JAR.previous
