Cleanup.

diff --git a/minecraft-server b/minecraft-server
--- a/minecraft-server
+++ b/minecraft-server
@@ -27,16 +27,13 @@
 # and need to download yours from someplace else you only need to change these 
 # setings. 
 
-# Your Minecraft version
+# Your Minecraft version (this is a preference only), script will always
+# get the latest Minecraft if it does not find a local server.
 MINECRAFT_VERSION=Latest
 
 # Your local Minecraft directory.
 MINECRAFT_HOME=~/bin/minecraft.server/Minecraft.$MINECRAFT_VERSION
 MINECRAFT_JAR=server.jar
-
-# Location of the start script and the anounce script for Minecraft
-MCSTART_URL=https://github.com/vonschutter/Ubuntu-Minecraft-Server-Manager/raw/master/bin/minecraft.server/Minecraft.Latest
-
 
 
 
@@ -50,22 +47,24 @@ MCSTART_URL=https://github.com/vonschutter/Ubuntu-Minecraft-Server-Manager/raw/m
 #
 
 function check_dependencies (){
-#---------------------------------------------------------------
-echo "Checking for script dependencies and install if not there..."
-#---------------------------------------------------------------
-    if hash "$1" 2>/dev/null; then
-        echo "I found that $1 is present on this system... thankyou for that! "
-    else
-        echo "You seem to have no $1... I will try to get it... "
-        install_software "$1"
-            if [ $? != 0 ];
-            then
-                echo "That install didn't work out so well."
-                echo "Please manually try to add the software since I couldn't do it."
-                exit
-            fi
-        echo "OK Done! Continuing..."
-    fi
+	# Simple function to check if sofware is available and take action 
+	# if it is not. Software name must match command to envoke it.
+	#---------------------------------------------------------------
+	echo "Checking for script dependencies and install if not there..."
+	#---------------------------------------------------------------
+	if hash "$1" 2>/dev/null; then
+		echo "I found that $1 is present on this system... thankyou for that! "
+	else
+		echo "You seem to have no $1... I will try to get it... "
+		install_software "$1"
+		if [ $? != 0 ];
+		then
+			echo "That install didn't work out so well."
+			echo "Please manually try to add the software since I couldn't do it."
+			exit
+		fi
+		echo "OK Done! Continuing..."
+	fi
 }
 
 function install_software (){
@@ -187,6 +186,9 @@ function find_active_newtork_interface (){
 #::::::::::::::    Script internal config repository     ::::::::::::::::::::::
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+# This section contains content to written out to several configuration
+# files and external scripts. 
+
 
 announce.py () {
 	cat >> $1/announce.py <<-'EOF'
@@ -194,8 +196,8 @@ announce.py () {
 #              RTD System System Managment Script
 # :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 # :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-# :: Author:     Stephan S. 
-# :: Version 1.01
+# :: Author:     generated by minecraft.server 
+# :: Version 1.02
 # ::
 # ::
 # :: Purpose: The purpose of the script is to:
@@ -206,25 +208,11 @@ announce.py () {
 # :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 # :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-
-# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-# :::::::::::::                                          ::::::::::::::::::::::
-# :::::::::::::          Script init                     ::::::::::::::::::::::
-# :::::::::::::                                          ::::::::::::::::::::::
-# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 import socket
 import time
 import sys
 import os
 import urllib.request
-
-
-# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-# :::::::::::::                                          ::::::::::::::::::::::
-# :::::::::::::          Script Executive                ::::::::::::::::::::::
-# :::::::::::::                                          ::::::::::::::::::::::
-# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-
 
 servers = [
     ["Local Network - Minecraft Server", 25565],
@@ -260,7 +248,7 @@ start.sh () {
 #::             RTD System System Managment Script
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#:: Author:     Stephan S. 
+#:: Author:     generated by minecraft.server 
 #:: Version 1.00
 #::
 #::
@@ -272,13 +260,6 @@ start.sh () {
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-
-
-#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#::::::::::::::                                          ::::::::::::::::::::::
-#::::::::::::::          Script Executive                ::::::::::::::::::::::
-#::::::::::::::                                          ::::::::::::::::::::::
-#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
 pushd $(dirname "$0")
 
@@ -307,8 +288,8 @@ exit
 
 server.properties () {
 	cat >> $1/server.properties <<-'EOF'
-#Minecraft server properties
-#Sun Apr 28 13:04:16 CEST 2019
+# Minecraft server properties
+# generated by minecraft.server
 broadcast-rcon-to-ops=true
 view-distance=6
 max-build-height=256
